### ISSUE TITLE
点击按钮没有反应

### ISSUE THREAD

**Issue by lawvs** [Co2333/myyearwithgit#8]
没有找到可用的日志。。。

```
OS Version:       macOS 11.2 (Build 20D64)
Architecture:     arm64e
```

https://user-images.githubusercontent.com/18554747/145583784-84af04e1-69f3-4ca7-abfe-e58aee87087f.mov

**Comment by Co2333** [comment]
昨天也有同学反馈了 这应该是个系统bug 升级一下吧 捂脸

**Comment by lawvs** [comment]
升级到 `macOS 12.0.1` 之后程序能够正常运行
